version: 2

jobs:
  build:
    parallelism: 2
    working_directory: ~/src
    docker:
    - image: circleci/ruby:2.5.1-node
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: pirc

    steps:
    - checkout

    - run:
        name: Install bundler
        command: gem install bundler

    - run:
        command: bundle exec rake db:create db:schema:load --trace

    - run:
        name: Rubocop
        command: bundle exec rubocop

    - run:
        command: bundle exec rspec

