require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2.1

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/api/v1/helpers/base.rb'

Metrics/LineLength:
  Max: 190

Metrics/BlockLength:
  Exclude:
    - 'app/api/v1/helpers/base.rb'
    - 'spec/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - 'db/migrate/**/*'

Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/**/*'

Rails/InverseOf:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NumericLiterals:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 5
