# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.5.1'

gem 'rails', '~>5.2.1'

# api
gem 'grape', '1.1.0'
gem 'grape-entity'
gem 'grape-swagger-entity'

gem 'rack-cors', require: 'rack/cors'

gem 'puma'

# postregsql
gem 'pg', '1.1.2 '

# ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.12'

group :development, :test do
  gem 'factory_bot_rails', '4.11.0'
  gem 'faker'
  gem 'pry'

  gem 'rspec-rails'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rspec'
end
